SRC@src := \
	src/vector/vector/ft_vector_reverse_rotate.c \
	src/vector/vector/ft_vector_find_index.c \
	src/vector/vector/ft_vector_clone.c \
	src/vector/vector/ft_vector_concat.c \
	src/vector/vector/ft_hvector_free.c \
	src/vector/vector/ft_vector_reverse.c \
	src/vector/vector/ft_vector_write.c \
	src/vector/vector/ft_vector_pop_back.c \
	src/vector/vector/ft_vector_alloc_from.c \
	src/vector/vector/ft_vector_extend.c \
	src/vector/vector/ft_vector_remove_at.c \
	src/vector/vector/ft_vector_sort.c \
	src/vector/vector/ft_vector_insert_many_at.c \
	src/vector/vector/ft_hvector_alloc.c \
	src/vector/vector/ft_vector_pop_front.c \
	src/vector/vector/ft_vector_get_error.c \
	src/vector/vector/ft_vector_push_back.c \
	src/vector/vector/ft_vector_safe_get.c \
	src/vector/vector/ft_vector_execute_for_each.c \
	src/vector/vector/ft_vector_find_first.c \
	src/vector/vector/ft_vector_get_size.c \
	src/vector/vector/ft_vector_erase.c \
	src/vector/vector/ft_vector_rotate.c \
	src/vector/vector/ft_hvector_get_value.c \
	src/vector/vector/ft_vector_auto_resize.c \
	src/vector/vector/ft_vector_swap_at.c \
	src/vector/vector/ft_vector_insert_at.c \
	src/vector/vector/ft_vector_alloc.c \
	src/vector/vector/ft_vector_push_front.c \
	src/vector/vector/ft_vector_set_flags.c \
	src/vector/vector/ft_vector_get_header.c \
	src/vector/vector/ft_vector_get_last.c \
	src/vector/vector/ft_vector_find_last.c \
	src/vector/vector/ft_vector_clear.c \
	src/vector/vector/info/ft_vector_info_normalize.c \
	src/vector/vector/ft_vector_match_every.c \
	src/vector/vector/ft_vector_match_some.c \
	src/vector/vector/ft_vector_get_first.c \
	src/vector/vector/ft_vector_find_last_index.c \
	src/vector/vector/ft_vector_get_flags.c \
	src/vector/vector/ft_vector_free.c \
	src/vector/vector/ft_vector_shrink_to_fit.c \
	src/vector/vector/ft_vector_get_safe_space.c \
	src/vector/vector/ft_vector_get.c \
	src/vector/vector/ft_vector_is_empty.c \
	src/vector/vector/ft_vector_resize.c \
	src/vector/vecstream/ft_stream_open_vector.c \
	src/string/string/ft_concat.c \
	src/string/string/ft_strchr.c \
	src/string/string/ft_split.c \
	src/string/string/ft_strtrim.c \
	src/string/string/ft_smsplit.c \
	src/string/string/ft_strnstr.c \
	src/string/string/ft_strmapi.c \
	src/string/string/ft_memmem.c \
	src/string/string/ft_strdup.c \
	src/string/string/ft_strisempty.c \
	src/string/string/ft_strcmp.c \
	src/string/string/ft_substr.c \
	src/string/string/ft_memchr.c \
	src/string/string/ft_strlcpy.c \
	src/string/string/ft_memset.c \
	src/string/string/ft_strlen.c \
	src/string/string/ft_streq.c \
	src/string/string/ft_strresize.c \
	src/string/string/ft_memccpy.c \
	src/string/string/ft_strlcat.c \
	src/string/string/ft_memcmp.c \
	src/string/string/ft_strrchr.c \
	src/string/string/ft_strneq.c \
	src/string/string/ft_strncmp.c \
	src/string/string/ft_memcpy.c \
	src/string/string/ft_memmove.c \
	src/string/string/ft_memswap.c \
	src/string/string/ft_strjoin.c \
	src/string/format/ft_aformat.c \
	src/string/format/ft_vaformat.c \
	src/string/format/ft_format.c \
	src/string/format/ft_vformat.c \
	src/string/strstream/ft_stream_open_string.c \
	src/string/wstring/ft_wcslen.c \
	src/memory/memory/ft_nullguard.c \
	src/memory/memory/ft_nullexit.c \
	src/memory/memory/ft_calloc.c \
	src/memory/memory/ft_realloc.c \
	src/memory/memory/ft_malloc.c \
	src/memory/memory/ft_free_each.c \
	src/memory/memory/ft_free_array.c \
	src/memory/memory/ft_free.c \
	src/memory/memory/ft_reallocarray.c \
	src/memory/gc/ft_gc_track.c \
	src/memory/gc/ft_gc_untrack.c \
	src/memory/gc/ft_gc_free_all.c \
	src/memory/gc/ft_gc_init.c \
	src/memory/memstream/ft_stream_open_memory.c \
	src/convert/ft_atoi.c \
	src/convert/ft_basedigit.c \
	src/convert/ft_itoa.c \
	src/array/ft_arrget.c \
	src/array/ft_arrswap.c \
	src/array/ft_arrlen.c \
	src/array/ft_qsort.c \
	src/array/ft_arrcpy.c \
	src/array/ft_arrmove.c \
	src/array/ft_arrresize.c \
	src/terminal/termutils/cursor_offset.c \
	src/terminal/termutils/cursor_line.c \
	src/terminal/termutils/corsor_position.c \
	src/terminal/termutils/color.c \
	src/ctype/ft_isprint.c \
	src/ctype/ft_tolower.c \
	src/ctype/ft_toupper.c \
	src/ctype/ft_isascii.c \
	src/ctype/ft_isdigit.c \
	src/ctype/ft_isalpha.c \
	src/ctype/ft_isalnum.c \
	src/ctype/ft_isspace.c \
	src/process/env/ft_unsetenv.c \
	src/process/env/ft_try_set_clearenv_exit_hook.c \
	src/process/env/ft_putenv.c \
	src/process/env/ft_set_clearenv_exit_hook.c \
	src/process/env/ft_clearenv.c \
	src/process/env/ft_getenv.c \
	src/process/env/ft_reallocenv.c \
	src/process/env/ft_setenv.c \
	src/process/env/ft_envinfo.c \
	src/utils/ft_freepass.c \
	src/utils/ft_deref.c \
	src/utils/ft_exitf.c \
	src/utils/ft_exit.c \
	src/debug/assert/ft_assert.c \
	src/math/ft_xmap.c \
	src/math/ft_abs.c \
	src/math/ft_clamp.c \
	src/math/ft_sign.c \
	src/math/ft_minmax_int.c \
	src/math/ft_minmax_float.c \
	src/math/ft_zsign.c \
	src/math/ft_rad_deg.c \
	src/math/ft_map.c \
	src/io/printf/ft_vprintf.c \
	src/io/printf/ft_printf.c \
	src/io/printf/parser/parse_placeholder.c \
	src/io/printf/parser/parse_flags.c \
	src/io/printf/parser/parse_width.c \
	src/io/printf/parser/parse_size.c \
	src/io/printf/parser/parse_type.c \
	src/io/printf/parser/parse_precision.c \
	src/io/printf/parser/parse_uint.c \
	src/io/printf/ft_sprintf.c \
	src/io/printf/printers/print_pointer.c \
	src/io/printf/printers/print_float.c \
	src/io/printf/printers/print_value.c \
	src/io/printf/printers/print_signed.c \
	src/io/printf/printers/print_character.c \
	src/io/printf/printers/print_string.c \
	src/io/printf/printers/print_unsigned.c \
	src/io/input/ft_get_all.c \
	src/io/input/ft_get_char.c \
	src/io/input/ft_get_string.c \
	src/io/input/ft_get_until.c \
	src/io/input/ft_get_line.c \
	src/io/stream/stream_buffer/ft_stream_buffer_append.c \
	src/io/stream/stream_buffer/ft_stream_buffer_create.c \
	src/io/stream/stream_buffer/ft_stream_buffer_destroy.c \
	src/io/stream/stream_buffer/ft_stream_buffer_extract.c \
	src/io/stream/stream_buffer/ft_stream_buffer_set_limit.c \
	src/io/stream/stream/ft_stream_is.c \
	src/io/stream/stream/ft_stream_clear_error.c \
	src/io/stream/stream/ft_stream_write.c \
	src/io/stream/stream/ft_stream_flush.c \
	src/io/stream/stream/ft_stream_direct_write.c \
	src/io/stream/stream/ft_stream_use_buffer.c \
	src/io/stream/stream/ft_stream_raise_error.c \
	src/io/stream/stream/ft_stream_direct_read.c \
	src/io/stream/stream/ft_stream_create.c \
	src/io/stream/stream/ft_stream_read.c \
	src/io/stream/stream/ft_stream_close.c \
	src/io/stream/stream_utils/ft_iosequence.c \
	src/io/stream/stream_utils/ft_ioguard.c \
	src/io/output/ft_put_line.c \
	src/io/output/ft_put_int.c \
	src/io/output/ft_put_string.c \
	src/io/output/ft_putf_int.c \
	src/io/output/ft_put_character.c \
	src/io/output/ft_put_float.c \
	src/io/fdstream/ft_stream_open_fd.c \
	src/io/fdstream/ft_cstd.c \
	src/tuples/ft_doublen.c \
	src/tuples/ft_floatn.c \
	src/tuples/ft_intn.c \
	src/x/functional/ft_lambda.c \
	src/x/algorithm/comparators/ft_compd.c \
	src/x/algorithm/comparators/ft_comp.c \
	src/x/algorithm/comparators/ft_compi.c \
	src/x/algorithm/comparators/ft_comps.c \
	src/x/algorithm/ft_sort.c \
